language: node_js

node_js:
  - "12"

before_install:
  npm install -g yarn

install:
  yarn install

before_deploy:
  yarn build:site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
